name: Deploy to Cloudflare Workers Sites

on:
  push:
    branches:
      - main

jobs:
  deploy-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Latest Version of Hugo
        uses: peaceiris/actions-hugo@2e89aa66d0093e4cd14751b3028fc1a179452c2e
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo Site
        run: |
          hugo --minify --gc
      - name: Publish to Cloudflare Workers Sites
        run: |
          echo "prefix = \"${HOME}\"" > ~/.npmrc
          npm install -g @cloudflare/wrangler
          mkdir -p ~/.wrangler/config/
          echo "api_token=\"${CF_API_TOKEN}\"" > ~/.wrangler/config/default.toml
          ~/bin/wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
